name: algbio
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.8.20
  - setuptools=75.1.0
  - sqlite=3.45.3
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.44.0
  - pip:
      - biopython==1.83
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.55.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - llvmlite==0.41.1
      - matplotlib==3.7.5
      - numba==0.58.1
      - numpy==1.24.4
      - packaging==24.2
      - pillow==10.4.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - six==1.16.0
      - zipp==3.20.2
